[package]
name = "rusty_enet"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.50"
wasm-timer = "0.2.5"

[dev-dependencies]
rand = "0.8.5"
rand_chacha = "0.3.1"

[workspace]
resolver = "2"
members = [
    "ci"
]
