[package]
name = "rusty_enet"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.69"

[dev-dependencies]
rand = "0.8.5"
rand_chacha = "0.3.1"

[workspace]
resolver = "2"
members = [
    "ci"
]
